on:
  push:
    branches:
      - "master"
jobs:
  updateFixVer:
    name: "UpdateFixVer"
    runs-on: ubuntu-latest
    steps:
      - name: "Get git log"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: "gh-actions"
          token: ${{ github.token }}
      - name: "FixVersion"
        uses: osleg/gh-actions@v1
